services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: parking
      POSTGRES_USER: parking
      POSTGRES_PASSWORD: parking
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parking -d parking"]
      interval: 5s
      timeout: 3s
      retries: 20

    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: parking
      RABBITMQ_DEFAULT_PASS: parking
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  db_data:
